### ISSUE TITLE
does this lib works widely?

### ISSUE THREAD

**Issue by emma-eva** [LvMalware/vfwd#1]
I mean, world wide access from their internet to local web server?

if i host my website locally then can people access to my local server using this tunnel and port forwarding lib?

If yes then i want to say not working (i tried in windows wsl, just works same pc network), if no then what need to do then?

**Comment by LvMalware** [comment]
Not really. The purpose of this tool is to perform pivoting inside a network (e.g: access an internal network trough a gateway host).
If you want to expose a local port on your machine to the internet, a tool like [ngrok](https://ngrok.com/) or [bore](https://github.com/ekzhang/bore) would work better.
